name: Send SMS

on:
  repository_dispatch:
    types: [sms]

jobs:
  send_sms:
    runs-on: ubuntu-latest
    steps:
    - name: Echo SMS
      run: |
        echo "📞 Phone: ${{ github.event.client_payload.phone }}"
        echo "✉️ Message: ${{ github.event.client_payload.message }}"
